name: Deploy to PyPi

on:
  release:
    types: [published]

jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Hatch
        run: pipx install hatch
      - name: Build dist
        run: hatch build
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/*
          if-no-files-found: error

  publish:
    name: Publish release to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/astronomer-snowpatrol-plugin
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: dist
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
